name: vhii
channels:
  - defaults
dependencies:
  - cudatoolkit=10.0
  - pip=20.0.2
  - python=3.6.3
  - pip:
    - cupy==7.7.0
    - numpy
    - pandas
    - Pillow
    - torch==1.2.0
    - torchvision==0.4.0
