name: vhii
channels:
  - defaults
dependencies:
  - ca-certificates=2020.7.22=0
  - cudatoolkit=10.0
  - pip=22.0.2
  - python=3.6.3
  - pip:
    - cupy==7.7.0
    - numpy
    - pandas
    - Pillow
    - torch==1.2.0
    - torchvision==0.4.0
