name: vhii
channels:
  - defaults
dependencies:
  - cudatoolkit
  - pip:
    - cupy==7.7.0
    - google-auth
    - google-auth-oauthlib
    - numpy
    - pandas
    - Pillow
    - torch==1.2.0
    - torchvision==0.4.0
