name: vhii
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20
  - cudatoolkit=10.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.0.2u
  - pip=20.0.2
  - python=3.6.3
  - readline=7.0
  - setuptools=47.1.1
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py
    - appdirs
    - astor
    - attrs
    - backcall
    - bleach
    - cachetools
    - cffi
    - cPython
    - cupy==7.7.0
    - cycler
    - Cython
    - decorator
    - defusedxml
    - entrypoints
    - fastrlock
    - filelock
    - future
    - gast
    - google-auth
    - google-auth-oauthlib
    - grpcio
    - h5py
    - idna
    - imageio
    - importlib-metadata
    - ipykernel
    - ipython
    - ipython-genutils
    - jedi
    - Jinja2
    - joblib
    - jsonschema
    - jupyter-client
    - jupyter-core
    - Keras-Applications
    - Keras-Preprocessing
    - kiwisolver
    - lmdb
    - Mako
    - Markdown
    - MarkupSafe
    - matplotlib
    - mistune
    - nbconvert
    - nbformat
    - networkx
    - nose
    - notebook
    - numpy
    - oauthlib
    - olefile
    - opencv-python
    - packaging
    - pandas
    - pandocfilters
    - parso
    - pexpect
    - pickleshare
    - Pillow
    - prometheus-client
    - prompt-toolkit
    - protobuf
    - ptyprocess
    - pyasn1
    - pyasn1-modules
    - pybind11
    - pycparser
    - pycuda==2019.1.2
    - Pygments
    - pymongo
    - pyparsing
    - pypi
    - pyrsistent
    - python-dateutil
    - pytools
    - pytz
    - PyWavelets
    - PyYAML
    - pyzmq
    - requests
    - requests-oauthlib
    - rsa
    - scikit-image
    - scikit-learn
    - scipy
    - Send2Trash
    - six
    - tensorboard
    - tensorboard-plugin-wit
    - tensorboardX
    - tensorflow-gpu==1.12.0
    - termcolor
    - terminado
    - testpath
    - thop
    - threadpoolctl
    - tifffile
    - torch==1.2.0
    - torchvision==0.4.0
    - tornado
    - tqdm
    - traitlets
    - typing-extensions
    - urllib3
    - wcwidth
    - webencodings
    - Werkzeug
    - zipp
